FROM rabbitmq:3.8.9-management-alpine

RUN wget -O /opt/rabbitmq/plugins/rabbitmq_message_deduplication-0.5.0.ez https://github.com/noxdafox/rabbitmq-message-deduplication/releases/download/0.5.0/rabbitmq_message_deduplication-0.5.0.ez && \
    wget -O /opt/rabbitmq/plugins/elixir-1.10.4.ez https://github.com/noxdafox/rabbitmq-message-deduplication/releases/download/0.5.0/elixir-1.10.4.ez && \
    wget -O /opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.8.9-0199d11c.ez https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.8.9/rabbitmq_delayed_message_exchange-3.8.9-0199d11c.ez && \
    rabbitmq-plugins enable rabbitmq_message_deduplication rabbitmq_delayed_message_exchange
