version: '3.7'

services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq

    image: rabbitmq:3.8.9-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmqpw"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - .queuelog/:/var/log/rabbitmq
      - .queuedata/:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "25672:5672"
